//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentASM_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHang", Namespace="http://schemas.datacontract.org/2004/07/PaymentServiceASM")]
    [System.SerializableAttribute()]
    public partial class DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SoTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentASM_Client.ServiceReference1.Payment[] PaymentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDHField, value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKHField, value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MaDT {
            get {
                return this.MaDTField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDTField, value) != true)) {
                    this.MaDTField = value;
                    this.RaisePropertyChanged("MaDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal SoTien {
            get {
                return this.SoTienField;
            }
            set {
                if ((this.SoTienField.Equals(value) != true)) {
                    this.SoTienField = value;
                    this.RaisePropertyChanged("SoTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string statusDH {
            get {
                return this.statusDHField;
            }
            set {
                if ((object.ReferenceEquals(this.statusDHField, value) != true)) {
                    this.statusDHField = value;
                    this.RaisePropertyChanged("statusDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PaymentASM_Client.ServiceReference1.Payment[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/PaymentServiceASM")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaGDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PhiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenGDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaGD {
            get {
                return this.MaGDField;
            }
            set {
                if ((this.MaGDField.Equals(value) != true)) {
                    this.MaGDField = value;
                    this.RaisePropertyChanged("MaGD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Phi {
            get {
                return this.PhiField;
            }
            set {
                if ((this.PhiField.Equals(value) != true)) {
                    this.PhiField = value;
                    this.RaisePropertyChanged("Phi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenGD {
            get {
                return this.TenGDField;
            }
            set {
                if ((object.ReferenceEquals(this.TenGDField, value) != true)) {
                    this.TenGDField = value;
                    this.RaisePropertyChanged("TenGD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDHField, value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoiTac", Namespace="http://schemas.datacontract.org/2004/07/PaymentServiceASM")]
    [System.SerializableAttribute()]
    public partial class DoiTac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MKDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaTKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentASM_Client.ServiceReference1.DonHang[] DonHangsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDT {
            get {
                return this.MaDTField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDTField, value) != true)) {
                    this.MaDTField = value;
                    this.RaisePropertyChanged("MaDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MKDT {
            get {
                return this.MKDTField;
            }
            set {
                if ((object.ReferenceEquals(this.MKDTField, value) != true)) {
                    this.MKDTField = value;
                    this.RaisePropertyChanged("MKDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MaTK {
            get {
                return this.MaTKField;
            }
            set {
                if ((object.ReferenceEquals(this.MaTKField, value) != true)) {
                    this.MaTKField = value;
                    this.RaisePropertyChanged("MaTK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PaymentASM_Client.ServiceReference1.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaiKhoan", Namespace="http://schemas.datacontract.org/2004/07/PaymentServiceASM")]
    [System.SerializableAttribute()]
    public partial class TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaTKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SoTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentASM_Client.ServiceReference1.DoiTac[] DoiTacsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaTK {
            get {
                return this.MaTKField;
            }
            set {
                if ((object.ReferenceEquals(this.MaTKField, value) != true)) {
                    this.MaTKField = value;
                    this.RaisePropertyChanged("MaTK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SoTien {
            get {
                return this.SoTienField;
            }
            set {
                if ((this.SoTienField.Equals(value) != true)) {
                    this.SoTienField = value;
                    this.RaisePropertyChanged("SoTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PaymentASM_Client.ServiceReference1.DoiTac[] DoiTacs {
            get {
                return this.DoiTacsField;
            }
            set {
                if ((object.ReferenceEquals(this.DoiTacsField, value) != true)) {
                    this.DoiTacsField = value;
                    this.RaisePropertyChanged("DoiTacs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/PaymentServiceASM")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SoTienTKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PaymentASM_Client.ServiceReference1.DonHang[] DonHangsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((object.ReferenceEquals(this.MaKHField, value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPin {
            get {
                return this.MaPinField;
            }
            set {
                if ((this.MaPinField.Equals(value) != true)) {
                    this.MaPinField = value;
                    this.RaisePropertyChanged("MaPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SoTienTK {
            get {
                return this.SoTienTKField;
            }
            set {
                if ((this.SoTienTKField.Equals(value) != true)) {
                    this.SoTienTKField = value;
                    this.RaisePropertyChanged("SoTienTK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PaymentASM_Client.ServiceReference1.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkyDonHang", ReplyAction="http://tempuri.org/IPaymentService/dangkyDonHangResponse")]
        void dangkyDonHang(PaymentASM_Client.ServiceReference1.DonHang dh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkyDonHang", ReplyAction="http://tempuri.org/IPaymentService/dangkyDonHangResponse")]
        System.Threading.Tasks.Task dangkyDonHangAsync(PaymentASM_Client.ServiceReference1.DonHang dh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/thanhtoanKH", ReplyAction="http://tempuri.org/IPaymentService/thanhtoanKHResponse")]
        void thanhtoanKH(PaymentASM_Client.ServiceReference1.Payment pm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/thanhtoanKH", ReplyAction="http://tempuri.org/IPaymentService/thanhtoanKHResponse")]
        System.Threading.Tasks.Task thanhtoanKHAsync(PaymentASM_Client.ServiceReference1.Payment pm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllPay", ReplyAction="http://tempuri.org/IPaymentService/getAllPayResponse")]
        PaymentASM_Client.ServiceReference1.Payment[] getAllPay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllPay", ReplyAction="http://tempuri.org/IPaymentService/getAllPayResponse")]
        System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.Payment[]> getAllPayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkyDoitac", ReplyAction="http://tempuri.org/IPaymentService/dangkyDoitacResponse")]
        void dangkyDoitac(PaymentASM_Client.ServiceReference1.DoiTac dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkyDoitac", ReplyAction="http://tempuri.org/IPaymentService/dangkyDoitacResponse")]
        System.Threading.Tasks.Task dangkyDoitacAsync(PaymentASM_Client.ServiceReference1.DoiTac dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllDoiTac", ReplyAction="http://tempuri.org/IPaymentService/getAllDoiTacResponse")]
        PaymentASM_Client.ServiceReference1.DoiTac[] getAllDoiTac();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllDoiTac", ReplyAction="http://tempuri.org/IPaymentService/getAllDoiTacResponse")]
        System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.DoiTac[]> getAllDoiTacAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkytaikhoan", ReplyAction="http://tempuri.org/IPaymentService/dangkytaikhoanResponse")]
        void dangkytaikhoan(PaymentASM_Client.ServiceReference1.TaiKhoan tk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkytaikhoan", ReplyAction="http://tempuri.org/IPaymentService/dangkytaikhoanResponse")]
        System.Threading.Tasks.Task dangkytaikhoanAsync(PaymentASM_Client.ServiceReference1.TaiKhoan tk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllTK", ReplyAction="http://tempuri.org/IPaymentService/getAllTKResponse")]
        PaymentASM_Client.ServiceReference1.TaiKhoan[] getAllTK();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllTK", ReplyAction="http://tempuri.org/IPaymentService/getAllTKResponse")]
        System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.TaiKhoan[]> getAllTKAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkyKH", ReplyAction="http://tempuri.org/IPaymentService/dangkyKHResponse")]
        void dangkyKH(PaymentASM_Client.ServiceReference1.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/dangkyKH", ReplyAction="http://tempuri.org/IPaymentService/dangkyKHResponse")]
        System.Threading.Tasks.Task dangkyKHAsync(PaymentASM_Client.ServiceReference1.KhachHang kh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllKH", ReplyAction="http://tempuri.org/IPaymentService/getAllKHResponse")]
        PaymentASM_Client.ServiceReference1.KhachHang[] getAllKH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllKH", ReplyAction="http://tempuri.org/IPaymentService/getAllKHResponse")]
        System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.KhachHang[]> getAllKHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/checkDT", ReplyAction="http://tempuri.org/IPaymentService/checkDTResponse")]
        bool checkDT(string madt, string mkdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/checkDT", ReplyAction="http://tempuri.org/IPaymentService/checkDTResponse")]
        System.Threading.Tasks.Task<bool> checkDTAsync(string madt, string mkdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/checkKH", ReplyAction="http://tempuri.org/IPaymentService/checkKHResponse")]
        bool checkKH(string makh, int mapin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/checkKH", ReplyAction="http://tempuri.org/IPaymentService/checkKHResponse")]
        System.Threading.Tasks.Task<bool> checkKHAsync(string makh, int mapin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllDH", ReplyAction="http://tempuri.org/IPaymentService/getAllDHResponse")]
        PaymentASM_Client.ServiceReference1.DonHang[] getAllDH();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/getAllDH", ReplyAction="http://tempuri.org/IPaymentService/getAllDHResponse")]
        System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.DonHang[]> getAllDHAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : PaymentASM_Client.ServiceReference1.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<PaymentASM_Client.ServiceReference1.IPaymentService>, PaymentASM_Client.ServiceReference1.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dangkyDonHang(PaymentASM_Client.ServiceReference1.DonHang dh) {
            base.Channel.dangkyDonHang(dh);
        }
        
        public System.Threading.Tasks.Task dangkyDonHangAsync(PaymentASM_Client.ServiceReference1.DonHang dh) {
            return base.Channel.dangkyDonHangAsync(dh);
        }
        
        public void thanhtoanKH(PaymentASM_Client.ServiceReference1.Payment pm) {
            base.Channel.thanhtoanKH(pm);
        }
        
        public System.Threading.Tasks.Task thanhtoanKHAsync(PaymentASM_Client.ServiceReference1.Payment pm) {
            return base.Channel.thanhtoanKHAsync(pm);
        }
        
        public PaymentASM_Client.ServiceReference1.Payment[] getAllPay() {
            return base.Channel.getAllPay();
        }
        
        public System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.Payment[]> getAllPayAsync() {
            return base.Channel.getAllPayAsync();
        }
        
        public void dangkyDoitac(PaymentASM_Client.ServiceReference1.DoiTac dt) {
            base.Channel.dangkyDoitac(dt);
        }
        
        public System.Threading.Tasks.Task dangkyDoitacAsync(PaymentASM_Client.ServiceReference1.DoiTac dt) {
            return base.Channel.dangkyDoitacAsync(dt);
        }
        
        public PaymentASM_Client.ServiceReference1.DoiTac[] getAllDoiTac() {
            return base.Channel.getAllDoiTac();
        }
        
        public System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.DoiTac[]> getAllDoiTacAsync() {
            return base.Channel.getAllDoiTacAsync();
        }
        
        public void dangkytaikhoan(PaymentASM_Client.ServiceReference1.TaiKhoan tk) {
            base.Channel.dangkytaikhoan(tk);
        }
        
        public System.Threading.Tasks.Task dangkytaikhoanAsync(PaymentASM_Client.ServiceReference1.TaiKhoan tk) {
            return base.Channel.dangkytaikhoanAsync(tk);
        }
        
        public PaymentASM_Client.ServiceReference1.TaiKhoan[] getAllTK() {
            return base.Channel.getAllTK();
        }
        
        public System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.TaiKhoan[]> getAllTKAsync() {
            return base.Channel.getAllTKAsync();
        }
        
        public void dangkyKH(PaymentASM_Client.ServiceReference1.KhachHang kh) {
            base.Channel.dangkyKH(kh);
        }
        
        public System.Threading.Tasks.Task dangkyKHAsync(PaymentASM_Client.ServiceReference1.KhachHang kh) {
            return base.Channel.dangkyKHAsync(kh);
        }
        
        public PaymentASM_Client.ServiceReference1.KhachHang[] getAllKH() {
            return base.Channel.getAllKH();
        }
        
        public System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.KhachHang[]> getAllKHAsync() {
            return base.Channel.getAllKHAsync();
        }
        
        public bool checkDT(string madt, string mkdt) {
            return base.Channel.checkDT(madt, mkdt);
        }
        
        public System.Threading.Tasks.Task<bool> checkDTAsync(string madt, string mkdt) {
            return base.Channel.checkDTAsync(madt, mkdt);
        }
        
        public bool checkKH(string makh, int mapin) {
            return base.Channel.checkKH(makh, mapin);
        }
        
        public System.Threading.Tasks.Task<bool> checkKHAsync(string makh, int mapin) {
            return base.Channel.checkKHAsync(makh, mapin);
        }
        
        public PaymentASM_Client.ServiceReference1.DonHang[] getAllDH() {
            return base.Channel.getAllDH();
        }
        
        public System.Threading.Tasks.Task<PaymentASM_Client.ServiceReference1.DonHang[]> getAllDHAsync() {
            return base.Channel.getAllDHAsync();
        }
    }
}
