//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAPPracClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/EAPPracServices")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentID {
            get {
                return this.StudentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIDField, value) != true)) {
                    this.StudentIDField = value;
                    this.RaisePropertyChanged("StudentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((this.PhoneNumberField.Equals(value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPracticeServices")]
    public interface IPracticeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPracticeServices/setStudent", ReplyAction="http://tempuri.org/IPracticeServices/setStudentResponse")]
        void setStudent(EAPPracClient.ServiceReference1.Student st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPracticeServices/setStudent", ReplyAction="http://tempuri.org/IPracticeServices/setStudentResponse")]
        System.Threading.Tasks.Task setStudentAsync(EAPPracClient.ServiceReference1.Student st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPracticeServices/getAllStudent", ReplyAction="http://tempuri.org/IPracticeServices/getAllStudentResponse")]
        EAPPracClient.ServiceReference1.Student[] getAllStudent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPracticeServices/getAllStudent", ReplyAction="http://tempuri.org/IPracticeServices/getAllStudentResponse")]
        System.Threading.Tasks.Task<EAPPracClient.ServiceReference1.Student[]> getAllStudentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPracticeServicesChannel : EAPPracClient.ServiceReference1.IPracticeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PracticeServicesClient : System.ServiceModel.ClientBase<EAPPracClient.ServiceReference1.IPracticeServices>, EAPPracClient.ServiceReference1.IPracticeServices {
        
        public PracticeServicesClient() {
        }
        
        public PracticeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PracticeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void setStudent(EAPPracClient.ServiceReference1.Student st) {
            base.Channel.setStudent(st);
        }
        
        public System.Threading.Tasks.Task setStudentAsync(EAPPracClient.ServiceReference1.Student st) {
            return base.Channel.setStudentAsync(st);
        }
        
        public EAPPracClient.ServiceReference1.Student[] getAllStudent() {
            return base.Channel.getAllStudent();
        }
        
        public System.Threading.Tasks.Task<EAPPracClient.ServiceReference1.Student[]> getAllStudentAsync() {
            return base.Channel.getAllStudentAsync();
        }
    }
}
